//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proyectofloresapi.Recursos.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Análisis y resultados.
        /// </summary>
        public static string _Layout_analisis {
            get {
                return ResourceManager.GetString("_Layout_analisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bloques.
        /// </summary>
        public static string _Layout_Bloques {
            get {
                return ResourceManager.GetString("_Layout_Bloques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo.
        /// </summary>
        public static string _Layout_Catalogo {
            get {
                return ResourceManager.GetString("_Layout_Catalogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fincas.
        /// </summary>
        public static string _Layout_Fincas {
            get {
                return ResourceManager.GetString("_Layout_Fincas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Índice.
        /// </summary>
        public static string _Layout_inicio {
            get {
                return ResourceManager.GetString("_Layout_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invernaderos.
        /// </summary>
        public static string _Layout_Invernaderos {
            get {
                return ResourceManager.GetString("_Layout_Invernaderos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producción.
        /// </summary>
        public static string _Layout_Produccion {
            get {
                return ResourceManager.GetString("_Layout_Produccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string _Layout_Usuarios {
            get {
                return ResourceManager.GetString("_Layout_Usuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error absoluto.
        /// </summary>
        public static string Analisis_Eabsoluto {
            get {
                return ResourceManager.GetString("Analisis_Eabsoluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencia absoluta.
        /// </summary>
        public static string Analisis_fabsoluta {
            get {
                return ResourceManager.GetString("Analisis_fabsoluta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencia acumulada.
        /// </summary>
        public static string Analisis_facumulada {
            get {
                return ResourceManager.GetString("Analisis_facumulada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite inferior.
        /// </summary>
        public static string Analisis_linferior {
            get {
                return ResourceManager.GetString("Analisis_linferior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite superior.
        /// </summary>
        public static string Analisis_lsuperior {
            get {
                return ResourceManager.GetString("Analisis_lsuperior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca de clase.
        /// </summary>
        public static string Analisis_mclase {
            get {
                return ResourceManager.GetString("Analisis_mclase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media.
        /// </summary>
        public static string Analisis_media {
            get {
                return ResourceManager.GetString("Analisis_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mediana.
        /// </summary>
        public static string Analisis_mediana {
            get {
                return ResourceManager.GetString("Analisis_mediana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de camas.
        /// </summary>
        public static string Analisis_ncamas {
            get {
                return ResourceManager.GetString("Analisis_ncamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producción flores.
        /// </summary>
        public static string Analisis_proflores {
            get {
                return ResourceManager.GetString("Analisis_proflores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Análisis de datos.
        /// </summary>
        public static string Analisis_titulo {
            get {
                return ResourceManager.GetString("Analisis_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diferencia al año.
        /// </summary>
        public static string Bloque_diferenciaaño {
            get {
                return ResourceManager.GetString("Bloque_diferenciaaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diferencia al mes.
        /// </summary>
        public static string Bloque_diferenciames {
            get {
                return ResourceManager.GetString("Bloque_diferenciames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar bloque registrado.
        /// </summary>
        public static string Bloque_edit {
            get {
                return ResourceManager.GetString("Bloque_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha registrado.
        /// </summary>
        public static string Bloque_fecha {
            get {
                return ResourceManager.GetString("Bloque_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producciones de bloques.
        /// </summary>
        public static string Bloque_lista {
            get {
                return ResourceManager.GetString("Bloque_lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llevamos al año.
        /// </summary>
        public static string Bloque_llevamos_año {
            get {
                return ResourceManager.GetString("Bloque_llevamos_año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llevamos al año.
        /// </summary>
        public static string Bloque_llevamosaño {
            get {
                return ResourceManager.GetString("Bloque_llevamosaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llevamos al mes.
        /// </summary>
        public static string Bloque_llevamosmes {
            get {
                return ResourceManager.GetString("Bloque_llevamosmes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de bloque.
        /// </summary>
        public static string Bloque_numero {
            get {
                return ResourceManager.GetString("Bloque_numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestado al año.
        /// </summary>
        public static string Bloque_ppto_año {
            get {
                return ResourceManager.GetString("Bloque_ppto_año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestado al  año.
        /// </summary>
        public static string Bloque_presupuestadoaño {
            get {
                return ResourceManager.GetString("Bloque_presupuestadoaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestado al mes.
        /// </summary>
        public static string Bloque_presupuestadomes {
            get {
                return ResourceManager.GetString("Bloque_presupuestadomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar producción bloque.
        /// </summary>
        public static string Bloque_registro {
            get {
                return ResourceManager.GetString("Bloque_registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string boton_editar {
            get {
                return ResourceManager.GetString("boton_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string boton_eliminar {
            get {
                return ResourceManager.GetString("boton_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string boton_guardar {
            get {
                return ResourceManager.GetString("boton_guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string boton_nuevo {
            get {
                return ResourceManager.GetString("boton_nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un invernadero.
        /// </summary>
        public static string Desplegable_invernadero {
            get {
                return ResourceManager.GetString("Desplegable_invernadero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin autorización.
        /// </summary>
        public static string Error_autorizacion {
            get {
                return ResourceManager.GetString("Error_autorizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Módulo.
        /// </summary>
        public static string Error_modulo {
            get {
                return ResourceManager.GetString("Error_modulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación.
        /// </summary>
        public static string Error_operacion {
            get {
                return ResourceManager.GetString("Error_operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes permiso.
        /// </summary>
        public static string Error_permiso {
            get {
                return ResourceManager.GetString("Error_permiso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a seleccione un departamento.
        /// </summary>
        public static string Finca_desplegable_departamento {
            get {
                return ResourceManager.GetString("Finca_desplegable_departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a seleccione un municipio.
        /// </summary>
        public static string Finca_desplegable_municipio {
            get {
                return ResourceManager.GetString("Finca_desplegable_municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar finca registrada.
        /// </summary>
        public static string Finca_edit {
            get {
                return ResourceManager.GetString("Finca_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es requerido.
        /// </summary>
        public static string Finca_errorm_nombre {
            get {
                return ResourceManager.GetString("Finca_errorm_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Municipio.
        /// </summary>
        public static string Finca_Lista_ciudad {
            get {
                return ResourceManager.GetString("Finca_Lista_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Finca_Lista_Id {
            get {
                return ResourceManager.GetString("Finca_Lista_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre finca.
        /// </summary>
        public static string Finca_Lista_nombre {
            get {
                return ResourceManager.GetString("Finca_Lista_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Departamento .
        /// </summary>
        public static string Finca_Lista_region {
            get {
                return ResourceManager.GetString("Finca_Lista_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar nueva finca.
        /// </summary>
        public static string Finca_rnueva {
            get {
                return ResourceManager.GetString("Finca_rnueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fincas registradas.
        /// </summary>
        public static string Fincas_registradas {
            get {
                return ResourceManager.GetString("Fincas_registradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este sistema de información esta desarrollado único y exclusivamente para los
        ///propietarios y administradores de las empresas de flores, si usted por algún motivo
        ///logro acceder sin hacer parte de alguno de estos dos últimos a los cuales se hace
        ///referencia, por favor salga del sistema y no haga mal uso de esta aplicación web..
        /// </summary>
        public static string Home_parrafo {
            get {
                return ResourceManager.GetString("Home_parrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido al sistema de información para la producción de flor..
        /// </summary>
        public static string Home_parrafo1 {
            get {
                return ResourceManager.GetString("Home_parrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SISTEMA DE INFORMACIÓN PRODUCCIÓN DE FLOR.
        /// </summary>
        public static string Home_Titulo {
            get {
                return ResourceManager.GetString("Home_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Invernadero Registrado.
        /// </summary>
        public static string Invernadero_edit {
            get {
                return ResourceManager.GetString("Invernadero_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {1} es requerido.
        /// </summary>
        public static string Invernadero_errorm_idfinca {
            get {
                return ResourceManager.GetString("Invernadero_errorm_idfinca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es requerido.
        /// </summary>
        public static string Invernadero_errorm_numero {
            get {
                return ResourceManager.GetString("Invernadero_errorm_numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finca.
        /// </summary>
        public static string Invernadero_finca {
            get {
                return ResourceManager.GetString("Invernadero_finca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Invernadero_id {
            get {
                return ResourceManager.GetString("Invernadero_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar nuevo invernadero.
        /// </summary>
        public static string invernadero_ingreso {
            get {
                return ResourceManager.GetString("invernadero_ingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invernaderos registrados.
        /// </summary>
        public static string invernadero_listregis {
            get {
                return ResourceManager.GetString("invernadero_listregis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número invernadero.
        /// </summary>
        public static string Invernadero_numero {
            get {
                return ResourceManager.GetString("Invernadero_numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una finca.
        /// </summary>
        public static string Invernadero_seleccionable {
            get {
                return ResourceManager.GetString("Invernadero_seleccionable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a acceder.
        /// </summary>
        public static string Login_boton_acceso {
            get {
                return ResourceManager.GetString("Login_boton_acceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Login_contraseña {
            get {
                return ResourceManager.GetString("Login_contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Login_usuario {
            get {
                return ResourceManager.GetString("Login_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        public static string Produccion_area {
            get {
                return ResourceManager.GetString("Produccion_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Camas.
        /// </summary>
        public static string Produccion_camas {
            get {
                return ResourceManager.GetString("Produccion_camas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar producción registrada.
        /// </summary>
        public static string Produccion_editar {
            get {
                return ResourceManager.GetString("Produccion_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id producción.
        /// </summary>
        public static string Produccion_id {
            get {
                return ResourceManager.GetString("Produccion_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producción id Bloque.
        /// </summary>
        public static string Produccion_idbloq {
            get {
                return ResourceManager.GetString("Produccion_idbloq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de semanas.
        /// </summary>
        public static string Produccion_nsemanas {
            get {
                return ResourceManager.GetString("Produccion_nsemanas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar producción.
        /// </summary>
        public static string Produccion_nueva {
            get {
                return ResourceManager.GetString("Produccion_nueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de plantas.
        /// </summary>
        public static string Produccion_plantas {
            get {
                return ResourceManager.GetString("Produccion_plantas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de produccion.
        /// </summary>
        public static string produccion_registrada {
            get {
                return ResourceManager.GetString("produccion_registrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un rol.
        /// </summary>
        public static string Seleccionable_rol {
            get {
                return ResourceManager.GetString("Seleccionable_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Usuario_apellidos {
            get {
                return ResourceManager.GetString("Usuario_apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula.
        /// </summary>
        public static string Usuario_cedula {
            get {
                return ResourceManager.GetString("Usuario_cedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Usuario_contraseña {
            get {
                return ResourceManager.GetString("Usuario_contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Usuario_correo {
            get {
                return ResourceManager.GetString("Usuario_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar usuario registrado.
        /// </summary>
        public static string Usuario_edit {
            get {
                return ResourceManager.GetString("Usuario_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres.
        /// </summary>
        public static string Usuario_nombres {
            get {
                return ResourceManager.GetString("Usuario_nombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol de usuario.
        /// </summary>
        public static string Usuario_rol {
            get {
                return ResourceManager.GetString("Usuario_rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar nuevo usuario.
        /// </summary>
        public static string Usuarios_newregis {
            get {
                return ResourceManager.GetString("Usuarios_newregis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios registrados.
        /// </summary>
        public static string Usuarios_regist {
            get {
                return ResourceManager.GetString("Usuarios_regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variedad de flor.
        /// </summary>
        public static string Variedad_flor {
            get {
                return ResourceManager.GetString("Variedad_flor", resourceCulture);
            }
        }
    }
}
